import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import MainNavbar from '../src/components/MainNavbar'
import DashboardNavbar from '../src/components/DashboardNavbar'
import DashboardContent from '../src/components/DashboardContent'
import Footer from '../src/components/Footer'
import styled from "../styles/Calender.module.css"
import { Box } from '@chakra-ui/react'
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Myxellia test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box display={{ md: "none", lg: "inline", sm: "none", base: "none" }}>
        <MainNavbar />

        <DashboardNavbar />
      </Box>
      <DashboardContent />
      <Footer />
    </div>
  );
}

export default Home
